### ISSUE TITLE
Error Float in Int64 

### ISSUE THREAD

**Issue by pauline-viguier** [WindVChen/DRENet#24]
Hi,  I tried to train Drenet Model with Pytorch version 1.9.0 but I've got this error : Traceback (most recent call last):   File "C:\Users\pauli\Documents\Detection_boat\DRENet\DRENet\train.py", line 521, in <module>     train(hyp, opt, device, tb_writer, wandb)   File "C:\Users\pauli\Documents\Detection_boat\DRENet\DRENet\train.py", line 300, in train     loss, loss_items, adaptParams = compute_loss(pred, dgimgs.to(device), targets.to(device))  # loss scaled by batch_size   File "C:\Users\pauli\Documents\Detection_boat\DRENet\DRENet\utils\loss.py", line 135, in __call__     tcls, tbox, indices, anchors = self.build_targets(p[0], targets)  # targets   File "C:\Users\pauli\Documents\Detection_boat\DRENet\DRENet\utils\loss.py", line 256, in build_targets     indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices RuntimeError: result type Float can't be cast to the desired output type __int64

If someone can help me, thanks !!!

**Comment by WindVChen** [comment]
Hi @pauline-viguier ,

There seems a discussion about this problem [[here](https://github.com/ultralytics/yolov5/issues/8405)]. A direct solution seems to change the version of Pytorch.

Also, you can also have a look at [[this blog](https://blog.csdn.net/weixin_54713879/article/details/125612388)], which presents how to modify the code to solve the issue.

Hope these help.
